### PR TITLE
MNT: Readme

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR mainly updates some elements that were still using `master` as branch name.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
The rendered [README.rst](https://github.com/GuillaumeFavelier/pyvistaqt/blob/7c7283ebf40194cf486a064c26e35716d7135bc6/README.rst) is available here:

https://github.com/GuillaumeFavelier/pyvistaqt/tree/7c7283ebf40194cf486a064c26e35716d7135bc6

This is ready for review from my side @pyvista/pyvistaqt-admin

**Comment by GuillaumeFavelier** [comment]
One more commit for a small typo :smile:

**Review by akaszynski — APPROVED** [review]
LGTM. Thanks!

**Comment by GuillaumeFavelier** [comment]
Thank you @akaszynski !

**Pull request merged**
