### PR TITLE
Add update-pr-branch action to update PR branch

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

The job of the action is to help click "Update branch" button for us. Designed to work with the `auto-merge` and ["Require branches to be up to date before merging"](https://docs.github.com/en/github/administering-a-repository/about-protected-branches#require-status-checks-before-merging) options. It will update the newest open PR that match the below conditions

- The PR has the `auto-merge` option enabled
- The PR has 1 approvals and no changes-requested review
- The PR branch has no conflicts with the base branch
- The PR branch is behind the base branch

image

### Details

- [Update PR Branch Action](https://github.com/adRise/update-pr-branch)

### CODE REVIEW

**Comment by tkoyama010** [comment]
LGTM

**Comment by larsoner** [comment]
I see how in principle this could help. But in practice if this had been in place when dependabot opened a ton of PRs, as soon as one was merged *all* of them would have been updated, creating quite a backlog/overkill in CI jobs. I almost think it's easier to manually update-and-merge one by one?

**Comment by tkoyama010** [comment]
> I see how in principle this could help. But in practice if this had been in place when dependabot opened a ton of PRs, as soon as one was merged _all_ of them would have been updated, creating quite a backlog/overkill in CI jobs. I almost think it's easier to manually update-and-merge one by one?

Thank you for your comment! This is actually to select one of the PRs and update only that one. Does that address your concern?

**Comment by larsoner** [comment]
Ahh okay I misunderstood -- let's try it then!

**Pull request merged**
