### PR TITLE
MNT: Test against different pyvista versions

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR follows https://github.com/pyvista/pyvistaqt/pull/109#issuecomment-843143140 and updates GitHub Actions matrix with `pyvista`.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
The `pyvista-master` jobs should return red until https://github.com/pyvista/pyvistaqt/pull/109 is merged.

**Comment by GuillaumeFavelier** [comment]
In `RangeGroup`, `setTickInterval()` expects an integer:

https://doc.qt.io/qt-5/qslider.html#tickInterval-prop

This went unnoticed and my guess is that the default value of `0.1` is just rounded to `0` (which is the default value anyway) :thinking:

**Comment by GuillaumeFavelier** [comment]
I did not know about this `ResourceWarning`, maybe I'll take care of it in the future but this is low priority for now.

This is ready for reviews @pyvista/developers

**Review by tkoyama010 — APPROVED** [review]
LGTM. It is good to test for diffrent pyvista versions. Thank you for MNT.

**Pull request merged**
