### PR TITLE
Add basic Editor

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR follows @banesullivan's idea in https://github.com/pyvista/pyvista-support/issues/182#issuecomment-645496798 and adds a (very) basic editor of the scene actor properties.

This is still a work in progress:

*I use a tiling window manager :sweat_smile:*

image

output

<details>
<summary>Code snippet</summary>

```py
import pyvista as pv
from pyvistaqt import BackgroundPlotter as Plotter

p = Plotter()
p.add_mesh(pv.Cone())
p.add_mesh(pv.Sphere(), name='Sphere')
p.add_mesh(pv.Cylinder(), name='Cylinder')
```

</details>

Also relevant to https://github.com/pyvista/pyvistaqt/issues/10

### CODE REVIEW

**Comment by akaszynski** [comment]
Nice!

**Comment by GuillaumeFavelier** [comment]
The latest version is more refined, this code could be used as canvas to add more UI elements. 

image

I use a protected member `_idx` while waiting to find a better connection between QTreeWidget and QStackedWidget. Once I have something, I'll work on testing.

**Comment by GuillaumeFavelier** [comment]
> I use a protected member _idx until I find a better connection between QTreeWidget and QStackedWidget.

I learned that it's possible to store user infos in a QTreeWidgetItem with [`setData()`](https://doc.qt.io/qt-5/qtreewidgetitem.html#setData).

Useful material: [stackoverflow](https://stackoverflow.com/questions/47076370/how-to-connect-qtreewidget-and-qstackedwidget-in-pyqt4)

**Comment by GuillaumeFavelier** [comment]
This is ready for reviews @pyvista/developers

**Review by akaszynski — APPROVED** [review]
I'm happy with this (and great job with the testing BTW).  We can also consider using `QIPythonWidget` to control position of the widgets in the future.  See:
https://github.com/akaszynski/pyvista-gui/blob/4ed7e3a52026dfeab4e82a300b92a92f43060dda/pyvista_gui/gui.py#L77

**Pull request merged**
