### PR TITLE
Work on codecov yaml

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR works on codecov.yml and try to fix the coverage badge. I want to see it green!

The goal is to have something working then iterate:

1) Remove a lot of defaults.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
I'm not sure it's because of the yaml file anymore. Something happened, either the coverage infos are not correct anymore or something is wrong during uploading:

image

**Comment by GuillaumeFavelier** [comment]
I'll restore the config file and investigate

**Comment by GuillaumeFavelier** [comment]
The difference I notice would be the report being XML instead of HTML. I would be surprised it that's the culprit tbh.

**Comment by GuillaumeFavelier** [comment]
There it is:

```
----------- coverage: platform linux, python 3.7.7-final-0 -----------
Name                    Stmts   Miss  Cover
-------------------------------------------
pyvistaqt/__init__.py       2      2     0%
pyvistaqt/_version.py       2      2     0%
pyvistaqt/plotting.py     419    419     0%
-------------------------------------------
TOTAL                     423    423     0%
```

**Comment by GuillaumeFavelier** [comment]
@akaszynski feel free to merge as it is if you're happy. Or let me know if you want me to also restore `codecov.yml`.

**Comment by akaszynski** [comment]
@GuillaumeFavelier, thanks for your hard work getting this figured out!

**Pull request merged**
