### PR TITLE
MNT: Qt binding testing

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
Qt binding is a sensitive topic. As @nicobako explained in https://github.com/pyvista/pyvistaqt/pull/61#issuecomment-705787742:

> Switching to qtpy means that it is now up to the user to have a qtpy-compatible Qt Python binding installed

I personally see great value in `PyVistaQt` being a light Qt interface over `PyVista`. And the support of both PyQt and PySide can only be big advantage for the project. Having `qtpy` is a step in the right direction but this is still not enough. Until now, only PyQt is tested meaning that PySide is let for unofficial support. That's why I volunteer to add Qt binding testing in this PR and I started by removing `PyQt5` as the default.

Please, let me know if you have a strong opinion against this approach @pyvista/developers 

Locally, I work on a conda environment with `PySide2` since `PySide6` is not supported on [`qtpy`](https://github.com/spyder-ide/qtpy/issues/229) yet. This is a work in progress.

Closes https://github.com/pyvista/pyvistaqt/issues/80

### CODE REVIEW

**Comment by larsoner** [comment]
My high-level comment is that I agree if PySide is meant to be officially supported it needs to be tested. I would make that happen in this PR and then in a follow-up PR work on Qt6 issues, since that's a separable issue.

**Comment by GuillaumeFavelier** [comment]
Strange how those linux jobs work with `PyQt5==5.11.3` but not with `5.15.1`.

We reproduce the issues encountered in https://github.com/pyvista/pyvistaqt/pull/59 basically

**Comment by GuillaumeFavelier** [comment]
I'll try updating the system from `ubuntu-16.04` to `ubuntu-18.04` but it will be my last try in this PR.

**Comment by GuillaumeFavelier** [comment]
I'm actually very tempted to use Github Actions for PySide testing instead of using a matrix in Azure. I suppose it will be more convenient for the reviewers too.

**Comment by GuillaumeFavelier** [comment]
Finally what I was waiting for:

```
RuntimeError: Available in PyQt5 only
```

**Comment by GuillaumeFavelier** [comment]
Only this issue on Windows remains when I try to install `opengl`:

```py
Cloning into 'gl-ci-helpers'...
ParentContainsErrorRecordException: D:\a\pyvistaqt\pyvistaqt\gl-ci-helpers\appveyor\install_opengl.ps1:15
Line |
  15 |      [Net.ServicePointManager]::SecurityProtocol = 'Ssl3, Tls, Tls11,  …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception setting "SecurityProtocol": "The requested security protocol is not supported."

Error: Process completed with exit code 1.
```

Any idea @akaszynski ?

**Comment by larsoner** [comment]
Probably old protocols that are no longer needed (?), e.g.:

https://mcpmag.com/articles/2020/04/02/microsoft-tls-1-0-and-1-1.aspx

I would try dropping TLS 1.1 in a PR to the gl-ci-helpers repo

**Comment by larsoner** [comment]
(and maybe you'll want to add a tiny Azure test for windows-latest in that repo to replicate first)

**Comment by GuillaumeFavelier** [comment]
It seems that SSL3 is not supported

**Comment by GuillaumeFavelier** [comment]
It is consistent with:
image

https://docs.microsoft.com/en-us/dotnet/api/system.net.securityprotocoltype?view=net-5.0#fields

**Comment by GuillaumeFavelier** [comment]
Next step is adding conda.

**Comment by GuillaumeFavelier** [comment]
Something in `environment.yml` introduces a dependency to `pyqt`.

**Comment by GuillaumeFavelier** [comment]
It's way better now. Indeed `matplotlib` was  the culprit.

**Comment by GuillaumeFavelier** [comment]
This is ready for reviews @pyvista/developers

**Comment by GuillaumeFavelier** [comment]
Optimally, I would prefer to merge this PR before https://github.com/pyvista/pyvistaqt/pull/78 so that I can update testing there.

**Review by larsoner — APPROVED** [review]
Looks like a pretty straightforward testing fix, thanks @GuillaumeFavelier

**Pull request merged**
