### PR TITLE
FIX: version

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR follows https://github.com/pyvista/pyvista/pull/965 and similarly updates the version.

Related to https://github.com/mne-tools/mne-python/pull/9291#issuecomment-821186527

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
Ready to go on my end @pyvista/developers

**Review by larsoner — APPROVED** [review]
Looks like the right change to me

**Comment by larsoner** [comment]
... actually no it doesn't. 0.3.0 is on PyPi, so this should probably be 0.4.dev0

**Comment by GuillaumeFavelier** [comment]
Thanks for checking this, I thought `0.3.dev0` would be enough

**Comment by larsoner** [comment]
It's probably enough to work around the MNE issue, but the convention I'm used to with projects is that once you release 0.3.0, you update the version to 0.4.dev0 or 0.4.0.dev0 or so. That way things like looseversion comparisons make it clear you're no longer on a 0.3 variant, but an upcoming 0.4 variant

**Comment by larsoner** [comment]
@GuillaumeFavelier you'll have to go on the Azure interface and restart the one failed job, I don't have permissions. If you don't have permissions we can close and reopen, or you can push an empty commit. It would be nice to just click the green button anyway since the linux failure is just a codecov upload problem, but looks like branch protection rules prohibit this

**Comment by GuillaumeFavelier** [comment]
I use some kind of trick to restart it in the GitHub interface. I can't restart with DevOps itself. Usually when a job fails, the `Re-run` or `Re-run failed jobs` is available somewhere here:

image

**Comment by GuillaumeFavelier** [comment]
Thanks for the reviews @larsoner !

**Pull request merged**
