### PR TITLE
Deploy sdist to PyPI

### LINKED ISSUE #22: Please publish sdist on PyPI
Currently, only binary wheels are published on PyPI. Could you please also publish the source distribution? This is relevant for users trying to build `pyvistaqt` themselves, or for creating `conda-forge` packages.

Thank you!

### PR DESCRIPTION
**Pull request by banesullivan**
Resolve #22

### CODE REVIEW

**Comment by banesullivan** [comment]
We'll likely have to push a patch release for this to land. Should we hold on that until #20 (and #15) is resolved?

**Comment by larsoner** [comment]
If the release process is automated anyway (e.g., kicked off by a GitHub / git release tag), I don't see a problem with not waiting and doing a couple quick releases.

**Comment by akaszynski** [comment]
> If the release process is automated anyway (e.g., kicked off by a GitHub / git release tag), I don't see a problem with not waiting and doing a couple quick releases.

Correct.  All we have to do is tag and it will be pushed.

**Comment by hoechenberger** [comment]
Nice! Are you planning to tag a new release?

**Comment by hoechenberger** [comment]
I saw you just did. Thank you!

**Pull request merged**
