### PR TITLE
Rename master to main

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR follows https://github.com/pyvista/pyvista/issues/1389 and updates internal refs.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
I think it would be a good idea to follow along and rename the `master` branch of `pyvistaqt` to `main`. What do you think @pyvista/developers ?

**Comment by akaszynski** [comment]
> I think it would be a good idea to follow along and rename the master branch of pyvistaqt to main.

Yes, for uniformity.  I'm doing this for the other repos.

**Comment by tkoyama010** [comment]
+1 Let's change!

**Review by tkoyama010 — APPROVED** [review]

**Comment by GuillaumeFavelier** [comment]
Thanks for the replies, I'll change the name now :)

**Pull request merged**
