### PR TITLE
Improve coverage

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR improves the coverage. I'll see how far I can go.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
I'm surprised there is no need for synchronization to test depth peeling and offscreen rendering. I would expect `waitExposed` to be needed, especially on MacOS. Good if it works without it.

Next is smoothing (polygon, line, etc...). From my experience this one is not compatible with Azure. I'll try anyway.

Except from that, the only part remaining for testing is drag & drop plus pinch gesture. AFAIK, those events are not available in `pytest-qt` so a hack will be necessary here.

**Comment by larsoner** [comment]
> Except from that, the only part remaining for testing is drag & drop plus pinch gesture. AFAIK, those events are not available in pytest-qt so a hack will be necessary here.

It would be better to first look into possibly adding them to `pytest-qt`. Not sure how complex it would be, though.

**Comment by GuillaumeFavelier** [comment]
> It would be better to first look into possibly adding them to pytest-qt

Sounds like a plan.

That will be all for this PR then.

More comments:
- I do not add any mesh in `test_depth_peeling`, `test_off_screen` and `test_smoothing`.
- Many tests use `test_background_plotting` in their name, I don't think it's necessary anymore.

**Comment by GuillaumeFavelier** [comment]
This is now ready for reviews @pyvista/developers !

**Comment by larsoner** [comment]
Thanks @GuillaumeFavelier

**Pull request merged**
