### PR TITLE
💚 Add Ipython test and check it in CI

### PR DESCRIPTION
**Pull request by tkoyama010**
See #49

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
@tkoyama010 I committed 9af5519e9bd17ca2776f4cf5258511e3f454c6f8 to test the CIs

**Comment by tkoyama010** [comment]
I added ipython.

**Comment by tkoyama010** [comment]
Test is pass but it has command error code :thinking:
https://dev.azure.com/pyvista/PyVista/_build/results?buildId=3534&view=logs&j=0d467bef-f31d-5157-7a21-e4463e6da84d&t=2a4bfbd9-68e3-5230-b53c-a804006f7915&l=36

**Comment by GuillaumeFavelier** [comment]
The failures on `Windows Python38-64bit` and `macOS Python37` seem to happen consistently.

**Comment by tkoyama010** [comment]
I have windows environment. So I could do the test of windows.

**Comment by GuillaumeFavelier** [comment]
> So I could do the test of windows.

That would be awesome :)

Meanwhile I will do 2 more tests with the CIs:

1) with the `qapp` fixture so that `pytest-qt` manages the `QApplication`
2) with `show=False`

**Comment by GuillaumeFavelier** [comment]
My changes didn't improve the situation

**Comment by tkoyama010** [comment]
:point_up: From https://stackoverrun.com/ja/q/11883985

**Comment by tkoyama010** [comment]
I reporoduce the error in Python3.8 in Windows10.

**Comment by tkoyama010** [comment]
:up: Let's split PyQt5 version up.

**Comment by tkoyama010** [comment]
This is ready for reviews @pyvista/developers @GuillaumeFavelier

**Review by larsoner — APPROVED** [review]
Looks straightforward so I'll merge, but @GuillaumeFavelier feel free to look when you get a chance

**Comment by larsoner** [comment]
Thanks @tkoyama010 !

**Comment by tkoyama010** [comment]
Thanks

**Pull request merged**
