### PR TITLE
Update doc with event loop explanation

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR adds a warning cell in the doc. It hopefully helps clear out some misunderstanding.

Closes https://github.com/pyvista/pyvistaqt/issues/74

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
Is it helpful @szsdk ?

**Comment by GuillaumeFavelier** [comment]
I think continuous integration require a bit of work :sweat_smile:

**Comment by szsdk** [comment]
@GuillaumeFavelier Great. That is definitely better.
In my opinion, changing "execute the Qt event loop with ``app.exec_()``" to
```
execute the Qt event loop by adding ``plotter.app.exec_()`` to the end of the following code
```
might be a little bit more clear.

**Comment by GuillaumeFavelier** [comment]
I'll update this after https://github.com/pyvista/pyvistaqt/pull/76 and hopefully we'll have more useful feedback from the CIs

**Review by larsoner — APPROVED** [review]

**Pull request merged**
